### ISSUE TITLE
Angular 컴포넌트 셀렉터 스타일링

### ISSUE THREAD

**Issue by hyesungoh** [hyesungoh/learningWhatIWant#14]
## 셀렉터 스타일링

```html
<app-foo>
</app-foo>
```

```css
:host {
  color: red
}
```

https://angular.io/guide/component-styles#host
