### ISSUE TITLE
CSS aspect-ratio 지원않는 브라우저 대응 방법

### ISSUE THREAD

**Issue by hyesungoh** [hyesungoh/learningWhatIWant#2]
## 비율을 고정시켜주는 css 속성 `aspect-ratio` 지원하지 않는 브라우저 대응 방법

```css
.foo {
  aspect-ratio: 1;

  @supports not (aspect-ratio: 1) {
    padding-top: 100%;
  }
}

.bar {
  aspect-ratio: 9 / 16;

  @supports not (aspect-ratio: 1) {
    padding-top: 56.25%;
  }
}
```

16:9 ratio -> 9 / 16 = 0.5625 -> `56.25%`
1:1 ratio -> 1 / 1 = 1.0 -> `100%`

css trick 링크
- https://css-tricks.com/aspect-ratio-boxes/#aa-the-core-concept-padding-in-percentages-is-based-on-width

mdn 링크
https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio

## Wrapper로써 사용해, padding 때문에 요소들이 내려갈 때

```html
<h1 class="aspect-ratio-box">
  <div class="aspect-ratio-box-inside">
    Happy Birthday
  </div>
</h1>
```

```css
.aspect-ratio-box {
  height: 0;
  overflow: hidden;
  padding-top: 100%;
  background: white;
  position: relative;
}
.aspect-ratio-box-inside {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```

css trick 링크
- https://css-tricks.com/aspect-ratio-boxes/#aa-how-do-you-put-content-inside-if-padding-is-pushing-everything-down

## pseudo element와 함께 사용하기

```jsx
const wrapperCss = css`
  max-width: 100%;
  aspect-ratio: 1;
  overflow: hidden;

  @supports not (aspect-ratio: 1) {
    position: relative;

    &::before {
      content: '';
      float: left;
      padding-top: 100%;
    }

    &::after {
      content: '';
      display: block;
      clear: both;
    }
  }
`;

const supportAspectRatioWrapperCss = css`
  width: 100%;
  height: 100%;

  @supports not (aspect-ratio: 1) {
    position: absolute;
    top: 0;
    left: 0;
    padding: 6px;
  }
`;
```
