### ISSUE TITLE
Storybook, Chromatic 설정 w/ Next.js, Yarn berry, Github actions

### ISSUE THREAD

**Issue by hyesungoh** [hyesungoh/learningWhatIWant#20]
# 스토리북 설정

storybook이 없는 프로젝트에서 다음 커맨드로 설정 가능

```bash
npx storybook@next init
```

필요에 따라 다음과 같이 `.storybook/main.ts` 설정

```ts
import path from 'path';

import type { StorybookConfig } from '@storybook/nextjs';

const config: StorybookConfig = {
  stories: ['../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    path.dirname(require.resolve(path.join('@storybook/addon-links', 'package.json'))),
    path.dirname(require.resolve(path.join('@storybook/addon-essentials', 'package.json'))),
    path.dirname(require.resolve(path.join('@storybook/addon-interactions', 'package.json'))),
  ],
  framework: {
    name: '@storybook/nextjs',
    options: {
      nextConfigPath: path.resolve(__dirname, '../next.config.js'),
    },
  },
  docs: {
    autodocs: 'tag',
  },
};

export default config;
```

## Yarn berry 라면

다음과 같은 추가 의존성이 필요

- @babel/core
- css-loader
- styled-jsx
- util
- webpack

```bash
yarn add -D @babel/core css-loader styled-jsx util webpack
```

# Chromatic 배포 w/ Github actions

chromatic cli가 pnp를 지원하지 않기 때문에 `nodeLinker`를 `node-modules`로 변경하는 작업이 필요

```yml
# .github/workflows/chromatic.yml

name: 'Chromatic'

on: # 필요에 따라 설정
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v3
        with: # 해당 옵션은 actions/checkout@v2 이상일 시 적용해야 함
          fetch-depth: 0 

      - name: Set node linker to nodeModules
        run: yarn config set nodeLinker "node-modules"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          buildScriptName: sb:build
          onlyChanged: true
```
